---
title: 迭代器与生成器
date: 2022-02-26 13:09:57
author: Jack-zhang
categories: TS
tags:
   - JS
   - TS
summary: 迭代器与生成器
---

## 迭代(iteration)

> 循环时迭代的基础:循环可以指定迭代的次数,以及每次需要执行什么操作

### 迭代器模式

>把实现了正式的`Iterable`接口的,并且可以通过迭代器`Iterator`使用的称做可选迭代器

```ts
//集合的元素可以按插入顺序访问每一个元素
let set = new Set<number>().add(1).add(2).add(3)
```

>实现可迭代协议(Iterable接口):要求同时具备两种能力

* 支持迭代的自我识别能力和创建实现`Iterator`接口的对象能力
* 在ESMA中,必须暴露一个属性`Symbol.iterator`作为默认迭代器
* 这个默认的迭代器属性必须使用一个迭代器工厂函数(调用时返回一个迭代器)

> 实现`Iterable`接口的类型

* string
* Array
* Map
* Set
* arguments
* NodeList等DOM集合

```ts
//可以通过这种方式是否存在默认的迭代器属性
console.log([][Symbol.iterator])
//[Function: values]
```

> 迭代器对象的原生语言

* `for...of`循环
* 数组解构
  
  ```ts
  const num:number[] = [1,2,3];
  let [a,b,c] = num;
  ```

* 扩展操作符`...`
* `Array.from()`
* `new Set()`
* `new Map()`
* `Promise.all()`接收promise组成的可迭代对象
* `Promise.race()`接收有promise组成的可迭代对象
* `yield*`操作符,在生成器中使用

> 迭代器使用`next()`方法在可迭代对象中遍历数据.

* 每成功调用`next()`都会返回一个`IteratorResult`对象,其中包含迭代器返回的下一个值
* `IteratorResult`包含两个属性:`done`和`value`.
  * done是一个布尔值,表示是否`next()`还可以再次调用取得下一个值
  * value是包含可迭代对象的下一个值(`done:false`或者undefined),如果done位true表示结束

```ts
let num: number[] = [1, 2]
let arr = num[Symbol.iterator]()
console.log(arr.next())//{ value: 1, done: false }
console.log(arr.next())//{ value: 2, done: false }
console.log(arr.next())//{ value: undefined, done: true }
```

* 只要迭代器对象到达`done:true`状态,后续调用`next`都是一样的值

## 生成器

>生成器可以在一个函数块内暂停和恢复代码执行的功能(自定义迭代器或者实现协程)

* 一般只需要在函数名前加一个`*`表示他是一个生成器.只要是可以定义函数的地方,就可以定义生成器
* 调用生成器函数会返回一个**生成器对象**.
  * 生成器对象一开始处于暂停执行的状态.与迭代器相似
  * 生成器对象同样实现了`Iterator`接口,因此具有next()方法
  * 在迭代器中,value值是函数的返回值.默认是undefined

```ts
function* gen() {
  return "value"
}
console.log(gen().next)//[Function: next]
console.log(gen().next())//{ value: 'value', done: true }
```

* <span style="color:red">生成器只会在初次调用`next()`方法后执行</span>.直接调用(例如`gen()`)并不会执行
* 生成器对象实现了`Iterable`接口,默认的迭代器是自引用的

### yield

>yield可以让生成器停止或者开始执行

* 生成器函数在遇到`yield`关键字之前会正常执行.遇到关键字之后,停止执行,函数作用域的状态会被保留
* 停止执行的生成器函数只能通过在生成器对象上调用`next()`方法来恢复执行
* 生成器是会被消费的,同一个生成器消费完后,不能再次被消费

> 通过`yield`关键字退出的生成器函数会处于`done:false`状态.而`return`关键字退出会处于`done:true`

```ts
function* gen() {
  yield "done"
  yield "data"
  return "value"
}
let genObj = gen()
console.log(genObj.next())//{ value: 'done', done: false }
console.log(genObj.next())//{ value: 'data', done: false }
console.log(genObj.next())//{ value: 'value', done: true }
```

>使用yield实现输入输出

* yield除了作为中间返回语句使用,还可以作为函数的中间参数使用.
* 上一次上生成器函数暂停的`yield`关键字会接收到传给`next()`方法的第一个值
* 但是第一次调用next()传入的值不会被使用,因为第一次是为了开始执行生成器函数

```ts
function* gen() {
  console.log(yield)
  console.log(yield)
}
let genObj = gen()
genObj.next(1)//不会打印任何东西
genObj.next(2)//2
genObj.next(3)//3
```

* 实现输入和输出

```ts
function* gen() {
  return yield 1
}
let genObj = gen()
console.log(genObj.next(3))//{ value: 1, done: false }
console.log(genObj.next(2))//{ value: 2, done: true }
```

1. 因为函数需要对整个表达式求值才能确定需要返回的值,所以在遇到yield关键字暂停并执行计算要产生的值`1`
2. 下一次调用`next()`会传入`2`,作为交给`yield`的值.确定位本次生成器函数要返回的值

>产生可迭代对象:可以使用`*`加强yield的行为,让他可以迭代一个可迭代对象,从而一次产出一个值

```ts
function* gen() {
  yield* [1, 2, 3]
}
for (let x of gen()) {
  console.log(x)
}//1  //2  //3
```

* 实际上`yield*`只是将一个可迭代的对象序列化为一连串的可以单独产出的值,所以这跟把`yield`凡在一个有循环里一样

```ts
function* gen() {
  for (let x of [1,2,3]){
    yield x
  }
}
```

> 提前终止生成器

* 一个实现`Iterator`接口的对象一定有next()方法,还有一个可选的`return()`方法用于提前终止迭代器.生成器除了有这两个方法,还有第三个方法`throw()`

1. `return()`:强制生成器进入关闭状态.提供给return()方法的值,就是迭代器对象的值
   * 在ts中,如果`reuturn()`需要传入参数,那么返回值return要定义好类型才能使用,否则`void`

   ```ts
   function* gen() {
     yield 1
     return 3
   }
   console.log(gen().return(4))
   //{ value: 1, done: true }
   ```

2. `throw`:会在暂停的时候将一个提供的错误注入到生成器对象.如果错误未被处理,生成器将会关闭
   * 如果生成器函数内部处理了这个错误,那么生成器就不会关闭,而且还可以恢复执行
   * 不过错误也会跳过相对应的yield.

   ```ts
   function* gen() {
     for (const x of [1, 2, 3]) {
       try {
         yield x
       } catch (e) {}
     }
   }
   const g = gen()
   console.log(g.next())//{ value: 1, done: false }
   g.throw("foo")
   console.log(g.next())//{ value: 3, done: false }
   ```

* 如果生成器对象还没有被执行,那么调用throw()抛出的错误不会在函数内部被捕获.因为这相当于在函数块外抛出了错误
  * 以下依然会抛出错误

  ```ts  
  function* gen() {
    for (const x of [1, 2, 3]) {
        try {
          yield x
        } catch (e) {}
        yield x
      }
  }
  const g = gen()
  g.throw("foo")
  console.log(g.next())
  console.log(g.next())
  ```

> 最后看一下Generator接口的写法

```ts
//Generator
interface Generator<T = unknown, TReturn = any, TNext = unknown> extends 
Iterator<T, TReturn, TNext> {
    next(...args: [] | [TNext]): IteratorResult<T, TReturn>;
    return(value: TReturn): IteratorResult<T, TReturn>;
    throw(e: any): IteratorResult<T, TReturn>;
    [Symbol.iterator](): Generator<T, TReturn, TNext>;
}

//Iterator
interface Iterator<T, TReturn = any, TNext = undefined> {
    next(...args: [] | [TNext]): IteratorResult<T, TReturn>;
    return?(value?: TReturn): IteratorResult<T, TReturn>;
    throw?(e?: any): IteratorResult<T, TReturn>;
}
```

* `Generator`泛型接收三个类型
  * **T**:yield后的参数类型
  * **Treturn**:return后的返回值类型
  * **TNext**:next()函数中的实参类型,不过如果指定了类型,可以不写,或者必须写对应的类型

> 使用生成器完成异步操作

```js
import * as fs from "fs/promises"

function* read() {
  const filePath = yield fs.readFile("index.txt", "utf8")
  return yield fs.readFile(filePath, "utf8")
}

function co(gen) {
  return new Promise((resolve, reject) => {
    const next = (data) => {
      const { value, done } = gen.next(data)
      if (done) {
        resolve(value)
      } else {
        Promise.resolve(value).then(res => {
          next(res)
        })
      }
    }
    next()
  })
}

const gen = co(read())
gen.then(res => console.log(res))
```
